### ISSUE TITLE
pystac ItemCollections unrecognized without installing `stackstac[viz]`

### ISSUE THREAD

**Issue by ljstrnadiii** [gjoseph92/stackstac#107]
I am trying an example posted [here](https://stackstac.readthedocs.io/en/latest/basic.html): 

```
lon, lat = -105.78, 35.79
items = catalog.search(
    intersects=dict(type="Point", coordinates=[lon, lat]),
    collections=["sentinel-s2-l2a-cogs"],
    datetime="2020-04-01/2020-05-01"
).get_all_items()
stack = stackstac.stack(items)
```

and am seeing

```
TypeError: Unrecognized STAC collection type <class 'pystac.item_collection.ItemCollection'>: <pystac.item_collection.ItemCollection object at 0x7f66a7efabe0>
```
Any ideas what is up?

**Comment by ljstrnadiii** [comment]
Looks like it happens with `pip install stackstac`. Instead I installed with `pip install 'stackstac[viz]'` and all is well.

**Comment by gjoseph92** [comment]
@ljstrnadiii I can reproduce this. You shouldn't have to install `stackstac[viz]` for this to work, so I'll look into it.

**Comment by gjoseph92** [comment]
Hm. I can no longer reproduce it.
```bash
python -m venv stackstac-venv
cd stackstac-venv
source bin/activate
pip install wheel
pip install --upgrade pip
pip install stackstac pystac-client
cat <<EOF > test.py
import stackstac
lon, lat = -105.78, 35.79

import pystac_client
URL = "https://earth-search.aws.element84.com/v0"
catalog = pystac_client.Client.open(URL)

items = catalog.search(
    intersects=dict(type="Point", coordinates=[lon, lat]),
    collections=["sentinel-s2-l2a-cogs"],
    datetime="2020-04-01/2020-05-01"
).get_all_items()

stack = stackstac.stack(items)
print(stack)
EOF
python test.py
```

@ljstrnadiii did you already have an older version of stackstac installed in your environment? If so, and you didn't pass `pip install --upgrade`, then pip wouldn't have installed the newest version of stackstac, which added support for pystac ItemCollections. But since you maybe didn't have `stackstac[viz]` installed, when you requested that, pip went and fetched the newest version?

**Comment by ljstrnadiii** [comment]
I probably did have an older version. I uninstalled and reinstalled rather than upgraded.
