### ISSUE TITLE
Missing file handling

### ISSUE THREAD

**Issue by RichardScottOZ** [gjoseph92/stackstac#12]
While looking at data in various areas, have come across missing bands, etc, yesterday this while testing stackstac:

  File "/home/ubuntu/anaconda3/envs/richard/lib/python3.8/site-packages/stackstac/rio_reader.py", line 393, in read
    reader = self.dataset
  File "/home/ubuntu/anaconda3/envs/richard/lib/python3.8/site-packages/stackstac/rio_reader.py", line 389, in dataset
    self._dataset = self._open()
  File "/home/ubuntu/anaconda3/envs/richard/lib/python3.8/site-packages/stackstac/rio_reader.py", line 330, in _open
    ds = SelfCleaningDatasetReader(rio.parse_path(self.url), sharing=False)
  File "rasterio/_base.pyx", line 262, in rasterio._base.DatasetBase.__init__
rasterio.errors.RasterioIOError: HTTP response code: 404

so perhaps can wrap this and report which one it failed on so can remove that and try again - and find out perhaps if a bad url or missing for the data provider end?

**Comment by RichardScottOZ** [comment]
e.g. was apparently this one after hacking this in for now  :-

File "/home/ubuntu/anaconda3/envs/richard/lib/python3.8/site-packages/stackstac/rio_reader.py", line 334, in _open
    raise RuntimeError(f"retrieval {self.url!r} problem" )
RuntimeError: retrieval 'https://sentinel-cogs.s3.us-west-2.amazonaws.com/sentinel-s2-l2a-cogs/22M/DU2020/8/S2A_22MDU_20200816_0_L2A/B02.tif' problem

**Comment by RichardScottOZ** [comment]
although now I see we have

title                   (band) object dask.array<chunksize=(1,), meta=np.ndarray>
[                                        ] | 0% Completed | 18.1shttps://sentinel-cogs.s3.us-west-2.amazonaws.com/sentinel-s2-l2a-cogs/22M/DU2020/8/S2A_22MDU_20200816_0_L2A/B02.tif retrieval error
[                                        ] | 0% Completed | 18.4s

**Comment by gjoseph92** [comment]
@RichardScottOZ yes, I've run into this too (STAC metadata isn't always that accurate!). We could raise a nicer error, sure. Would you want (an option) to just ignore these missing files, and treat them as all NaN?

That would be pretty easy: make a little class that follows this protocol but just returns `fill_value` of the right shape: https://github.com/gjoseph92/stackstac/blob/b652a07f9b2ae27235aea4db4ef0f1f594fd8941/stackstac/rio_reader.py#L81-L88

and if there's an errorr here https://github.com/gjoseph92/stackstac/blob/b652a07f9b2ae27235aea4db4ef0f1f594fd8941/stackstac/rio_reader.py#L330
return an instance of that dummy dataset class.

**Comment by RichardScottOZ** [comment]
Yes, a process that ignores them like that and continues would be excellent!

Some sort of missing data report would also be useful in that case - e.g. I had three scenes that were bad today in an area.

**Comment by gjoseph92** [comment]
Would raising a warning be okay? (With an option to turn them off too.)

**Comment by RichardScottOZ** [comment]
Yes, I would think so, something that allows you to easily see the name/id/etc for tracking them down.

**Comment by RichardScottOZ** [comment]
Having a look at this now - a dummy class wouldn't need a protocol?  (I am not clear on that part) - as there isn't one?
and just read and close methods?

If you hadn't mentioned the above my first thought would have probably been some sort of memory file raster to feed into one of your extant classes - ThreadLocalRioDataset etc.

**Comment by RichardScottOZ** [comment]
Just tested on my Brazil 'badlist' ran through ok.

```python
C:\Users\rscott\AppData\Local\Continuum\anaconda3\envs\stackstac\lib\site-packages\stackstac\rio_reader.py:355: UserWarning: Error opening 'https://sentinel-cogs.s3.us-west-2.amazonaws.com/sentinel-s2-l2a-cogs/22M/CV2020/8/S2A_22MCV_20200816_0_L2A/B02.tif': RasterioIOError('HTTP response code: 404')
  warnings.warn(msg)
C:\Users\rscott\AppData\Roaming\Python\Python38\site-packages\numpy\lib\nanfunctions.py:1113: RuntimeWarning: All-NaN slice encountered
  r, k = function_base._ureduce(a, func=_nanmedian, axis=axis, out=out,
[########################################] | 100% Completed |  2.6s
```
