### ISSUE TITLE
rasterio `parse_path` deprecation

### ISSUE THREAD

**Issue by TomAugspurger** [gjoseph92/stackstac#156]
Looks like rasterio is removing the `parse_path` method: https://github.com/rasterio/rasterio/issues/2365. It's used in a couple places

* https://github.com/gjoseph92/stackstac/blob/b1172defb8dc30c8502316f73228a42428f76753/stackstac/rio_reader.py#L327
* https://github.com/gjoseph92/stackstac/blob/b1172defb8dc30c8502316f73228a42428f76753/stackstac/rio_reader.py#L198

**Comment by carderne** [comment]
https://github.com/gjoseph92/stackstac/pull/155
