### ISSUE TITLE
Error caused by pyproj 3.4.0

### ISSUE THREAD

**Issue by julianblue** [gjoseph92/stackstac#173]
With the latest release of pyproj there seems to be an issue when running stackstac.stack with an epsg parameter. This does not occur when not specifying the epsg. 
Traceback below. 

Thanks in advance. 
![Screenshot 2022-09-12 at 16 31 51](https://user-images.githubusercontent.com/21318315/189682890-d93428f5-7514-45d0-8faf-09b80fc46576.png)

**Comment by gjoseph92** [comment]
@julianblue thanks for reporting! I'll try to get a release out fixing this in the next few days. For now, you could downgrade pyproj or install from my branch in https://github.com/gjoseph92/stackstac/pull/174.

**Comment by gjoseph92** [comment]
@julianblue stackstac=0.4.3 has been released on PyPi with this fix

cc @TomAugspurger

**Comment by TomAugspurger** [comment]
Just saw that, thanks :) I'll include it in our next round of updates when it gets through conda-forge.
