### ISSUE TITLE
Is there a way to reduce the logging verbosity?

### ISSUE THREAD

**Issue by jorge-cervest** [gjoseph92/stackstac#185]
Currently when stacking a large collection, I get lots of `INFO:stackstac.timer:Read` messages. I feel this should be a DEBUG level so I can filter it out.

Is there anyway to control this behaviour?

**Comment by jorge-cervest** [comment]
I just ended up setting the level at the logger 
`logging.getLogger('stackstac').setLevel(logging.ERROR)`

**Comment by gjoseph92** [comment]
Thanks for mentioning this. You're right that those should be switched to debug level. (Or removed entirely.)

Want to make a PR changing the default here to debug? https://github.com/gjoseph92/stackstac/blob/71a8362d98ef002de7e32bef8f1ea013a6964b49/stackstac/timer.py#L9

**Comment by jorge-cervest** [comment]
Done https://github.com/gjoseph92/stackstac/pull/186
