### ISSUE TITLE
README example raises `DoesNotConformTo`

### ISSUE THREAD

**Issue by ljstrnadiii** [gjoseph92/stackstac#220]
When trying to run this sentinel2 example as shown on the readme

```
import stackstac
import pystac_client

URL = "https://earth-search.aws.element84.com/v0"
catalog = pystac_client.Client.open(URL)

stac_items = catalog.search(
    intersects=dict(type="Point", coordinates=[-105.78, 35.79]),
    collections=["sentinel-s2-l2a-cogs"],
    datetime="2020-04-01/2020-05-01"
).get_all_items()

stack = stackstac.stack(stac_items)
print(stack)
```

The client is raising a `DoesNotConformTo`. Any ideas? 🙏 

Name: pystac-client
Version: 0.7.5
Name: pystac
Version: 1.8.3
Name: stackstac
Version: 0.4.3

**Comment by TomAugspurger** [comment]
I think EarthSearch is at https://earth-search.aws.element84.com/v1 now
(v1). And it seems like the collection names may have changed too. Does
using that newer endpoint work for you?

**Comment by ljstrnadiii** [comment]
Thanks, @TomAugspurger--I just figured this out. Yes, collection names have also changed:
```
list(
    pystac_client.Client.open(
        "https://earth-search.aws.element84.com/v1"
    ).get_children()
)
```
Gives:
```
 [<CollectionClient id=cop-dem-glo-30>,
 <CollectionClient id=naip>,
 <CollectionClient id=sentinel-2-l2a>,
 <CollectionClient id=sentinel-2-l1c>,
 <CollectionClient id=landsat-c2-l2>,
 <CollectionClient id=cop-dem-glo-90>,
 <CollectionClient id=sentinel-1-grd>] 
```
Looking at the `sentinel-2-l2a` collection shows they are cogs for each band, etc. Modifying the url and collection seems to work:

```
import stackstac
import pystac_client

URL = "https://earth-search.aws.element84.com/v1"
catalog = pystac_client.Client.open(URL)

stac_items = catalog.search(
    intersects=dict(type="Point", coordinates=[-105.78, 35.79]),
    collections=["sentinel-2-l2a"],
    datetime="2020-04-01/2020-05-01"
).get_all_items()

stack = stackstac.stack(stac_items)
print(stack)
```

**Comment by gjoseph92** [comment]
@ljstrnadiii interestingly, I don't get this error with older versions of pystac-client. Thanks for the catch, we might as well use the newer endpoint anyway.
