### ISSUE TITLE
High RAM use during stackstac.stack(items, epsg=item_crs) 

### ISSUE THREAD

**Issue by J6767** [gjoseph92/stackstac#227]
When I have >150 Sentinel-2 products in my pystac query, and then try to run:

`stack = stackstac.stack(items, epsg=item_crs) `

I am sometimes encountering >70GB of RAM usage. Is this expected behaviour and is there any workaround? I suspect it stems from the conversion between different CRS but, AFAIK, this is required, as I have found some variations in CRS between S2 products. Many thanks.

**Comment by gjoseph92** [comment]
This is definitely not expected behavior. Can you provide a reproducer and more info about your environment?

**Comment by gjoseph92** [comment]
Without a reproducible example, there's not much we can help with here, so I'm going to close this. @J6767, if you'd like to provide a reproducer, feel free to re-open.
