### ISSUE TITLE
Accessing VZA and SZA bands?

### ISSUE THREAD

**Issue by J6767** [gjoseph92/stackstac#229]
I need to calculate air mass factor (AMF), which requires viewing zenith angle (VZA), and solar zenith angle (SZA). 

If you manually download a Sentinel-2 product, the 2D band "sun_zenith" is found under "Bands/sun",  and "view_zenith_mean" is found under "Bands/view". 

They are also present in the metadata, as Values_list, under Geometric_Info/Tile_Angles.

How can I access these bands, or metadata, using stackstac, please? Many thanks.

**Comment by gjoseph92** [comment]
Hi @J6767, how are you accessing the data? Without a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), there's not much I can do to help, or even confirm whether it's an issue with stackstac, or with the data provider.
