### ISSUE TITLE
Protocol from typing

### ISSUE THREAD

**Issue by jaimebayes** [gjoseph92/stackstac#58]
Hi guys, 

I am trying to run the basics notebook on Colab, but it throws this error:
ImportError: cannot import name 'Protocol' from 'typing' (/usr/lib/python3.7/typing.py)
Any advice to fix this?
Thanks in advance, JL

**Comment by kylebarron** [comment]
That's because `stackstac` requires Python 3.8+
https://github.com/gjoseph92/stackstac/blob/2c799e3f0075942cbb76a99f96517d4fe15bc98a/pyproject.toml#L38

**Comment by jaimebayes** [comment]
Thanks, I will try again with this, JL
