### ISSUE TITLE
Puzzling behavior of accumulate_metadata (None and NaTs in coordinates)

### ISSUE THREAD

**Issue by scottyhq** [gjoseph92/stackstac#78]
I'm trying out stackstac with this valid STAC 1.0 static catalog here: 
https://github.com/scottyhq/sentinel1-rtc-stac/tree/main/12SYJ 

The following appears to work but is a bit slow (running in same region as data AWS us-west-2), and the `VisibleDeprecationWarning` caught my eye.
```python
import pystac
import stackstac
cat = pystac.read_file('https://raw.githubusercontent.com/scottyhq/sentinel1-rtc-stac/main/12SYJ/catalog.json')

%%time 
da = stackstac.stack(cat,
                     assets=['gamma0_vv'])
da
# CPU times: user 188 ms, sys: 12.5 ms, total: 201 ms
# Wall time: 3.5 s
# stackstac/accumulate_metadata.py:151: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences
```

Inspecting the time coordinate we get a `NaT`, which I've figure out happens when *only one* of the [Items having fractional seconds](https://github.com/scottyhq/sentinel1-rtc-stac/blob/main/12SYJ/2018/S1B_20180110_12SYJ_ASC/S1B_20180110_12SYJ_ASC.json#L76) in `datetime`, but the others do not.  

```python
da.time
"""
array(['2016-11-21T01:09:37.000000000', '2017-01-08T01:09:43.000000000',
       '2017-02-07T01:10:20.000000000', '2017-02-14T01:02:16.000000000',
       '2018-01-03T01:09:50.000000000',                           'NaT',
       '2018-01-15T01:09:50.000000000', '2019-01-10T01:09:57.000000000',
       '2019-01-22T01:09:56.000000000', '2019-02-03T01:09:56.000000000',
       '2020-08-31T13:18:20.000000000', '2020-09-07T13:10:16.000000000',
       '2020-09-12T13:18:20.000000000', '2021-01-05T13:10:15.000000000',
       '2021-01-10T13:18:18.000000000', '2021-01-17T13:10:14.000000000'],
"""
```

The 'NaT' disappears if you first normalize the timestamps:
```python
for item in cat.get_all_items():
    item.datetime = item.datetime.replace(microsecond=0)
    print(item.datetime)
```

But there are other 'None' values showing up in coordinates that have sets of unique values. I don't see any obvious issues in the metadata (which passes validation), so I'm suspecting a bug in stacstack based on the `VisibleDeprecationWarning`. See some of the other coordinates below with `None` values. Nones show up at the front of the coords and are not restricted to specific items...

```python
da['sat:orbit_state']
#array([None, None, None, None, None, None, None, None, None, 'ascending', 'descending', 'descending', 'descending', 'descending', 'descending', 'descending'], dtype=object)

da['platform']
#array([None, 'sentinel-1b', 'sentinel-1a', 'sentinel-1a', 'sentinel-1b','sentinel-1b', 'sentinel-1b', 'sentinel-1b', 'sentinel-1b','sentinel-1b', 'sentinel-1a', 'sentinel-1a', 'sentinel-1a','sentinel-1a', 'sentinel-1a', 'sentinel-1a'], dtype=object)

da['sat:relative_orbit']
#array([None, None, 49, 151, 49, 151, 49, 49, 49, 49, 129, 56, 129, 56, 129, 56], dtype=object)
```

**Comment by gjoseph92** [comment]
Hey @scottyhq, sorry I never looked into this. I suspect you're right, there's probably a bug in `accumulate_metadata` here. I don't think I'll have time to work on this for a while though—if you have the chance, please feel free to take a look!
