### ISSUE TITLE
Clarification on dependencies minimum versions

### ISSUE THREAD

**Issue by scottyhq** [gjoseph92/stackstac#83]
I was recently trying to install stackstac alongside the latest tensorflow (`conda create -n stackstack-ml tensorflow=2.6 stackstac`), but this fails due to incompatible numpy dependencies. In particular https://github.com/gjoseph92/stackstac/blob/662579f684c6b252b29407f02a233aaa794782dc/pyproject.toml#L32 

Translates to `numpy >=1.20.0,<2.0.0`  in the [conda-forge feedstock](https://github.com/conda-forge/stackstac-feedstock/blob/b98c9d8a1f9b7438012058d683bc20e4ba7d1a7e/recipe/meta.yaml#L27)

And `conda search tensorflow-base=2.6 --info` is quite strict with `numpy >=1.19.2,<1.20`

I realize this isn't really a bug with stackstac, but is 1.20 truly the minimum required version? Or just the last version being used during development? 

cc @ocefpaf who is the listed maintainer of the conda-forge feedstock.

**Comment by gjoseph92** [comment]
Interesting point. It probably isn't the minimum, but I'd want to check first.

**Comment by ocefpaf** [comment]
BTW, kind of unrelated but not :grimacing:, I use NEP-29 as a guide for my numpy support/tests: https://numpy.org/neps/nep-0029-deprecation_policy.html

**Comment by kylebarron** [comment]
FYI `rasterio` uses the [`oldest-supported-numpy`](https://pypi.org/project/oldest-supported-numpy/) package for this https://github.com/rasterio/rasterio/blob/ba5e90c487bd1930f52e57dba999e889b4df9ade/pyproject.toml#L2
