### ISSUE TITLE
Support non-NaN nodata values in `mosaic`

### ISSUE THREAD

**Issue by gjoseph92** [gjoseph92/stackstac#92]
From https://github.com/microsoft/PlanetaryComputerExamples/pull/108#discussion_r758370301.

Support a `nodata=np.nan` kwarg to `stackstac.mosaic`, so you can specify a different nodata value if that's what you're using.

The larger problem here is that we're not storing the nodata value in xarray metadata anywhere—just using the xarray convention that NaN _is_ the standard nodata value. But if you set `fill_value`, that's no longer the case.

Broadly related to https://github.com/gjoseph92/stackstac/issues/50: rioxarray has a [convention](https://corteva.github.io/rioxarray/stable/getting_started/nodata_management.html) for storing nodata in attributes, which we could follow, it's just convoluted CF-style. A single `nodata` coordinate might be more sensible to xarray users. (The real answer is native missing-value support in xarray though https://github.com/pydata/xarray/issues/4143 https://github.com/pydata/xarray/issues/3955 https://github.com/pydata/xarray/issues/1194.)

If we had this, `mosiac` could automatically use the nodata value stored in the data, not requiring you to keep track of it.

cc @TomAugspurger

**Comment by TomAugspurger** [comment]
Thanks I was debating whether or not to open this :) I'm probably OK with just a keyword.

I agree that this really needs to be solved upstream in xarray / NumPy.
